# theme: jekyll-theme-minimal
title: Little Richard Rock Set List
description: Set list for a Little Richard Rock Set.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
