# theme: jekyll-theme-minimal
title: Little Richard Style Set List
description: Chords for the songs played with the little richard style cover band.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
